{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dangiashish",
    "module": "geotagimage",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "geotagimage-1.2.3.aar",
          "url": "geotagimage-1.2.3.aar",
          "size": 105746,
          "sha512": "ad326ff2b79bb2e9452a86e418b9d1e1c04312e4baadf55e6b84a5f0c835f6d80db99401e75be01a04d2fbae92cef73930bd27430509e546cfb28f227f7f67dd",
          "sha256": "2a8199c18681d2fced10b6589b82d689dc485596d4119df41bdd8cc6508702e1",
          "sha1": "bcdbce9a3190e7c84a593e150e0895d5b0ae784a",
          "md5": "abaf8108c0ebef3eb166dcccd4ee0831"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "geotagimage-1.2.3.aar",
          "url": "geotagimage-1.2.3.aar",
          "size": 105746,
          "sha512": "ad326ff2b79bb2e9452a86e418b9d1e1c04312e4baadf55e6b84a5f0c835f6d80db99401e75be01a04d2fbae92cef73930bd27430509e546cfb28f227f7f67dd",
          "sha256": "2a8199c18681d2fced10b6589b82d689dc485596d4119df41bdd8cc6508702e1",
          "sha1": "bcdbce9a3190e7c84a593e150e0895d5b0ae784a",
          "md5": "abaf8108c0ebef3eb166dcccd4ee0831"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "geotagimage-1.2.3-sources.jar",
          "url": "geotagimage-1.2.3-sources.jar",
          "size": 37871,
          "sha512": "6066052ac952dc4f291cf1d0f3040d1c7aaa2bfbce830b82b5a4d6768bf73ff425a060e63cf3204081fb8f72bfadf9b09a098b29a456a386fcd345cb0300d0bf",
          "sha256": "c89554ef5a59d30d3ba3899eddc9f94ca3eab1bf87f58f261f0af8db2d1bb572",
          "sha1": "91a2da610f2625c5bcacaa9d438ba21c41a69bc4",
          "md5": "e5ec0b30d735df2e4691a2c7c2702078"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "geotagimage-1.2.3-javadoc.jar",
          "url": "geotagimage-1.2.3-javadoc.jar",
          "size": 343322,
          "sha512": "1f3a76ebfb0116b6b5f8a23953cb5e6d32bc6742b2da5b3ed68bee08324f94817b41611bc35ccca1a5cf60eb00b4a499a672162eb5a3cae9e37f0d17d5548b74",
          "sha256": "d61de755551b8c9e088561e19bce54f228fb96aef3403cc289317b55bc476cf2",
          "sha1": "20dacd4d7b0332c16d0020f48a58aa9c09d844c3",
          "md5": "c39befeaf3b585174c42b6f1ca074928"
        }
      ]
    }
  ]
}
