name: Android CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Uninstall  build-tool version 31.0.0
      run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager --uninstall 'build-tools;31.0.0'

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: GTI-Test-App.apk
        path: app/build/outputs/apk/debug/app-debug.apk
